menu:
  Home: /
  Archives: /archives
  About: /about

widgets:
- category
- tagcloud
- recent_posts

excerpt_link: Continue Reading →

mathjax: true
fancybox: true

duoshuo_shortname: shmilee-github

social:
  enable: true # 启用
  tsina: shmilee # 个性域名
  facebook: 
  google: 
  twitter: 
  github: shmilee # username 
  email: true # 在 root _config.yml 中填写
  rss: true
#  coderwall: 
#  stackoverflow: 
#  linkedin: 
#  pinterest: 
#  delicious: 
#  pinboard:

## 两个分享工具, 百度和addthis, enable一个即可

addthis:
  enable: false
  facebook: false
  twitter: true
  gplus: true
  pinit: false
  pubid:

bdshare:
  enable: true
  uid: 2030893
  douban: true
  qzone: true
  renren: true
  tsina: true # sina微博
  tqq: false # qq微博
  twi: true # twitter
  fbook: true # facebook
  hi: false # 百度hi
