menu:
  Home: 
  Archives: archives
  About: about

widgets:
- category
- tagcloud
- recent_posts

excerpt_link: Continue Reading →

mathjax: true
fancybox: true

duoshuo_shortname: shmilee-github

social:
  github: true
  rss: true

github:
  username: shmilee

## 两个分享工具, 百度和addthis, enable一个即可

addthis:
  enable: false
  facebook: false
  twitter: true
  gplus: true
  pinit: false
  pubid:

bdshare:
  enable: true
  uid: 2030893
  douban: true
  qzone: true
  renren: true
  tsina: true # sina微博
  tqq: false # qq微博
  twi: true # twitter
  fbook: true # facebook
  hi: false # 百度hi
